.TH djbdnscurve6: dnstxt 1
.SH NAME
dnstxt \- recursive query of TXT record for fqdn
.SH SYNOPSIS
.B dnstxt
.I fqdn
.SH DESCRIPTION
.B dnstxt
prints the TXT record of  
.I fqdn
on a single line.
If there is no TXT record,
.b dnstxt
prints a blank line.
.SH SEE ALSO
dnsip(1),
dnsname(1),
dnsmx(1),
dnsipq(1),
dnsqr(1),
dnsq(1),
dnstrace(1)
.SH REFERENCE
http://cr.yp.to/djbdns.html
