# Don't edit Makefile! Use ../conf-* for configuration.

SHELL=/bin/sh

default: one five eight

axfr-get.0: \
axfr-get.8
	nroff -man axfr-get.8 > axfr-get.0

axfrdns.0: \
axfrdns.8
	nroff -man axfrdns.8 > axfrdns.0

axfrdns-conf.0: \
axfrdns-conf.8
	nroff -man axfrdns-conf.8 > axfrdns-conf.0

clean: \
TARGETS
	rm -f `cat TARGETS`

curvedns-keygen.0: \
curvedns-keygen.8
	nroff -man curvedns-keygen.8 > curvedns-keygen.0

dnscache-conf.0: \
dnscache-conf.8
	nroff -man dnscache-conf.8 > dnscache-conf.0

dnscache-log.0: \
dnscache-log.5
	nroff -man dnscache-log.5 > dnscache-log.0

dnscache.0: \
dnscache.8
	nroff -man dnscache.8 > dnscache.0

dnsfilter.0: \
dnsfilter.1
	nroff -man dnsfilter.1 > dnsfilter.0

dnsip.0: \
dnsip.1
	nroff -man dnsip.1 > dnsip.0

dnsipq.0: \
dnsipq.1
	nroff -man dnsipq.1 > dnsipq.0

dnsmx.0: \
dnsmx.1
	nroff -man dnsmx.1 > dnsmx.0

dnsname.0: \
dnsname.1
	nroff -man dnsname.1 > dnsname.0

dnsq.0: \
dnsq.1
	nroff -man dnsq.1 > dnsq.0

dnsqr.0: \
dnsqr.1
	nroff -man dnsqr.1 > dnsqr.0

dnstrace.0: \
dnstrace.1
	nroff -man dnstrace.1 > dnstrace.0

dnstxt.0: \
dnstxt.1
	nroff -man dnstxt.1 > dnstxt.0

eight: \
axfr-get.0 axfrdns.0 axfrdns-conf.0 \
dnscache-conf.0 dnscache.0 \
rbldns-conf.0 rbldns-data.0 rbldns.0 \
tinydns-conf.0 tinydns-data.0 tinydns-edit.0 \
tinydns-get.0 tinydns.0 \
walldns-conf.0 walldns.0 \
curvedns-keygen.0

five: \
dnscache-log.0 qualification.0 tinydns-log.0

one:\
dnsfilter.0 dnsip.0 dnsipq.0 dnsmx.0 dnsname.0 \
dnsq.0 dnsqr.0 dnstrace.0 dnstxt.0

qualification.0: \
qualification.5
	nroff -man qualification.5 > qualification.0

rbldns-conf.0: \
rbldns-conf.8
	nroff -man rbldns-conf.8 > rbldns-conf.0

rbldns-data.0: \
rbldns-conf.8
	nroff -man rbldns-data.8 > rbldns-data.0

rbldns.0: \
rbldns.8
	nroff -man rbldns.8 > rbldns.0

tinydns-conf.0: \
tinydns-conf.8
	nroff -man tinydns-conf.8 > tinydns-conf.0

tinydns-data.0: \
tinydns-data.8
	nroff -man tinydns-data.8 > tinydns-data.0

tinydns-edit.0: \
tinydns-edit.8
	nroff -man tinydns-edit.8 > tinydns-edit.0

tinydns-log.0: \
tinydns-log.5
	nroff -man tinydns-log.5 > tinydns-log.0

tinydns-get.0: \
tinydns-get.8
	nroff -man tinydns-get.8 > tinydns-get.0

tinydns.0: \
tinydns.8
	nroff -man tinydns.8 > tinydns.0

walldns-conf.0: \
walldns-conf.8
	nroff -man walldns-conf.8 > walldns-conf.0

walldns.0: \
walldns.8
	nroff -man walldns.8 > walldns.0

